# image will be published to ghcr.io/<user>/<name>
name: azurite
# description will be included in the image's metadata
description: Bazzite with my personal changes.

alt-tags:
  - stable
  - latest

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: stable

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: signing

  - type: files
    files:
      - source: system
        destination: /

  - type: script
    snippets:
      - "echo \"\\\"Rootful Distrobox\\\" = \\\"/usr/bin/distrobox upgrade --root --all\\\"\" >> /usr/etc/ublue-os/topgrade.toml" # Add rootful distrobox to topgrade
      - "rm /usr/etc/profile.d/ublue-firstboot.sh" # Disable YAFTI
    scripts:
      - modify-image-info.sh
      - modify-fastfetch.sh
      - modify-os-release.sh

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode

  # Virtualization
  - type: rpm-ostree
    install:
      - virt-manager
      - edk2-ovmf
      - qemu

  # Docker
  - type: rpm-ostree
    install:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - docker-buildx-plugin
      - containerd.io

  # Misc
  - type: rpm-ostree
    install:
      - zsh
      - coolercontrol
      - liquidctl
      - code

  - type: systemd
    system:
      enabled:
        # Virtualization
        - libvirtd.service
        # Docker
        - docker.service
        - containerd.service
        - coolercontrold.service
    user:
      enabled:
        # Azurite Service
        - azurite-user-setup.service

