name: bluebuild
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".vscode/**"
  pull_request:
  workflow_dispatch: # allow manually triggering builds
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here
          # - recipe-azurite.yml
          - recipe-bazzite.yml
    steps:
      # the build is fully handled by the reusable github action
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
      - name: Inspect image and extract label
        run: |
          KERNEL_VALUE=$(skopeo inspect docker://ghcr.io/ublue-os/bazzite:stable | jq -r '.Labels["ostree.linux"] | capture("(?<a>.*-ogc.*)\\.(?<b>fc(?<c>[0-9]+))")')
          KERNEL_VERSION=$(echo $KERNEL_VALUE | jq -r '.a + "-" + .b')
          FEDORA_VERSION=$(echo $KERNEL_VALUE | jq -r '.c')
          echo "kernel_version=$KERNEL_VERSION" >> $GITHUB_ENV
          echo "fedora_version=$FEDORA_VERSION" >> $GITHUB_ENV
      - name: Display extracted labels
        run: |
          echo "Extracted ostree.linux label: $kernel_version"
          echo "Extracted Fedora version: $fedora_version"
      - name: Modify file with extracted label
        run: |
          sed -i "s/KERNEL_VERSION_PLACEHOLDER/$kernel_version/g" ./containerfiles/akmod/Containerfile
          sed -i "s/FEDORA_VERSION_PLACEHOLDER/$fedora_version/g" ./containerfiles/akmod/Containerfile
      - name: Build Custom Image
        uses: blue-build/github-action@24d146df25adc2cf579e918efe2d9bff6adea408 # v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true
          skip_checkout: true
